#!/usr/bin/env bash

bluetoothctl devices | awk '{print $2}' | while read -r mac_id; do
    bluetoothctl connect $mac_id
    # Cant actually break while reads :(
    #  | while read state; do
        # if [[ $tate == "Connection successful" ]]; then
            # echo "ended early"
            # break 2
        # fi
    # done
done
